### ISSUE TITLE
Authorization API

### ISSUE THREAD

**Issue by targos** [adonisjs/rfcs#26]
## Brief history

Once a user has been authenticated, it is a common need in most web applications to have an authorization phase that determines if the user is allowed to do specific actions. Without that, any authenticated user would be able to do anything and access everything.

## What problem does it solve?

This proposal aims to implement a low-level API that allows to manage authorization in a common way throughout the application without having to write complex conditions inside the controllers and helping to reduce code repetition if the same actions can be initiated in multiple places.  
The goal here is not to force the application developer into one specific way of doing authorization. It's rather to provide something that can be used either directly or to build something more complex on top of it (for example, RBAC).

## Proposal

The functionality will be accessible using a new Provider, which could be called `Adonis/Addons/Authorization`. This provider would depend on the presence of the [`auth`](https://github.com/adonisjs/auth) provider, which defines and gives access to the authenticated user.

This proposal is largely inspired by [Laravel's Authorization](https://laravel.com/docs/7.x/authorization) API. There are two main entities: Gates and Policies.

#### Implementation

A gate is a simple mapping between an action name and a callback function. It is defined by calling a static method on the `Gate` object. The action name can be any string value which conceptually represents what the user is trying to do. The callback will then be called each time this specific action must be authorized, with the user object and optionally other arguments. It must return a boolean value indicating if the user is allowed to do the action or not. The callback function is allowed to return a Promise, which will be awaited to extract the boolean value.

Because authorization is a feature tightly related to security, any value returned from a gate function that is not a boolean (or a Promise resolving to a boolean) will make the Gate methods throw an internal server error.

```js
// This file could be preloaded from `start/authorization.ts`.

// Implementation of the gates
import { Gate } from '@ioc:Adonis/Addons/Authorization';

// Simple gate that needs only the user
Gate.define('edit-settings', (user) => {
  return user.isAdmin;
});

// Gate with an additional parameter
Gate.define('update-post', (user, post) => {
  return user.id === post.userId;
});

// Gate with asynchronous verification
Gate.define('doSomething', async (user) => {
  const hasPermissions = await someAsyncService.verifyPermissions(user);
  return hasPermissions;
});
```

#### Usage whithin a request context

The authorization provider would add a Getter to the AdonisJS `HttpContext` providing access to a Gate instance associated to the authenticated user from any route or controller method.

The Gate can be used to check if the user is allowed or denied to do an action previously defined, or to automatically throw an authorization error resulting in a 403 Forbidden response:

```js
// In a route handler.
Route.post('/settings', async (ctx) => {
  if (await ctx.gate.allows('edit-settings')) {
    // User is allowed.
  }

  if (await ctx.gate.denies('edit-settings')) {
    // User is not allowed.
  }

  await ctx.gate.authorize('edit-settings'); // Throws if user is not allowed.
});

// In a controller
class PostController {
  update(ctx) {
    // Get the post that the user is trying to update.
    const post = await Post.findOrFail(ctx.params.id);

    await ctx.gate.authorize('update-post', post); // Throws if user is not allowed.
  }
}
```

#### Usage anywhere in the app

Outside of the `HttpContext`, a Gate instance could be created by getting a user object somehow (for example with a call to the database) and calling the `Gate.forUser` method:

```ts
import { Gate } from '@ioc:Adonis/Addons/Authorization';

export async function doSomething(userId: number) {
  const user = await User.findOrFail(userId);
  const gate = Gate.forUser(user);

  if (await gate.allows('doSomething')) {
    // User is allowed.
  }
}
```

#### TypeScript support

To fully support strong type checks in the whole API, it is proposed to define, like other existing providers such as [`events`](https://github.com/adonisjs/events), an empty interface that would be extended by the application developer, for example in `contracts/authorization.ts`:

```ts
import Post from 'App/Models/Post';

declare module '@ioc:Adonis/Addons/Authorization' {
  interface GateActions {
    'edit-settings': [];
    'update-post': [Post];
    doSomething: [];
  }
}
```

Each field of the interface is the name of the action, while its type is a tuple defining the types of the arguments which must be passed when authorizing that action. Note that the `User` type is not specified as it is always passed as the first argument.

This, I think is the most simple thing we can do to ensure that everything is correctly typed. The `Gate.define` method will only accept action names defined in this interface, same for the authorization methods which will then correctly hint to the developer (IntelliSense). After an action is selected, the type of the arguments will be checked and enforced correctly as well.

### Policies

Policies are a layer above gates to avoid potential naming conflicts in actions and allow to separate authorization functions in different files while colocating those that apply to the same kinds of objects.

They are implemented as classes in which each method is an authorization function. Models (or actually any class that represents a protected entity) are then mapped to a policy.

When Gate methods are called passing one of the mapped Models, the gate will check if there is a method on the related Policy. In that case, the method will be called with the User, the Model, and optionally additional arguments.

#### Create a Policy

A new Ace command will be added to create a new Policy:

```console
node ace make:policy PostPolicy
```

This will generate an empty `PostPolicy` class in `app/Policies/PostPolicy.ts`.

We could also support a `--model` flag to populate the class with "CRUD" method names, expecting instances of the passed Model.

#### Implement a Policy

There are two files to edit to actually implement a Policy. Let's assume that we have created the `PostPolicy` from above. Now `app/Policies/PostPolicy.ts` must be edited to actually implement the policy checks:

```ts
import Post from 'App/Models/Post';
import User from 'App/Models/User';

export default class PostPolicy {
  public create(user: User) {
    return user.isAdmin;
  }

  public update(user: User, post: Post) {
    return user.id === post.userId;
  }

  public delete() {
    return false; // Posts cannot be deleted by users.
  }
}
```

Additionnally, the mapping between the new policy and the `Post` model must be registered with the application's Gate. This is done in `start/authorization.ts`:

```ts
Gate.registerPolicies([
  [Post, PostPolicy],
  // ... all model/policy mappings are registered here
]);
```

#### Usage with gates

Once a policy has been registered, it can be used anywhere with a Gate object:

```ts
import Post from 'App/Models/Post';

export default class PostController {
  create(ctx) {
    // Note that we directly pass the `Post` constructor here. It doesn't have
    // to be an instance because there is no `Post` yet before we create it.
    if (await ctx.gate.allows('create', Post)) {
      // User is allowed to create.
    }
  }

  update(ctx) {
    // Get the post that the user is trying to update.
    const post = await Post.findOrFail(ctx.params.id);

    // This will call the `update` method on `PostPolicy`, passing the authenticated
    // User and the `post`.
    await ctx.gate.authorize('update', post); // Throws if user is not allowed.
  }
}
```

#### TypeScript support

In my PoC implementation, I have partial support for types, using the following setup.

Similar to Gate actions, the application developer must extend an originally empty interface:

```ts
import Post from 'App/Models/Post';
import PostPolicy from 'App/Policies/PostPolicy';

declare module '@ioc:Adonis/Addons/Authorization' {
  interface GatePolicies {
    Post: PolicyType<typeof Post, PostPolicy>;
  }
}
```

This allows to automatically extract all method names from each possible policy and determine the possible actions based on the Model that is passed in the gate methods.

It checks correctly that a valid action is passed depending on the Model.  
Unfortunately, I haven't found a way to make IntelliSense work (you cannot have it list the possible actions) and the additional arguments cannot be type checked.

## Open questions

- How to implement [guest users](https://laravel.com/docs/7.x/authorization#guest-users)?
  - This is not entirely clear to me how to implement it in a good way so that it works with TypeScript. I don't think it's a good idea to make the user parameter optional by default because it would require the developer to make a null check in all gates/policy methods.
- How to access the `User` type from the `auth` provider for correct automatic typing of the `user` parameter in all methods?
- Can we have better type support for Model/Policy mappings in gate methods?

## Out of scope

Laravel has some other interesting features that are not part of this proposal because I don't see them as critical for a first release but they could be added later without breaking the initial API.

- [before/after hooks](https://laravel.com/docs/7.x/authorization#intercepting-gate-checks)
- [policy filters](https://laravel.com/docs/7.x/authorization#policy-filters)
- [gate/policy responses](https://laravel.com/docs/7.x/authorization#gate-responses)
- [middleware shortcut](https://laravel.com/docs/7.x/authorization#via-middleware)

## Relevant links

- Authorization in Laravel: https://laravel.com/docs/7.x/authorization

## Are you willing to work on it?

Yes. I have already written some proof of concept code to implement a large part of the proposal.

**Comment by thetutlage** [comment]
I haven't read the complete RFC. But I believe, we can extract the types for the interface from the gate policies itself. Following is an hypothetical example.

```ts
export default Gate.withTypes(
  Gate.define('edit-settings', (user) => {
    return user.isAdmin;
  }),
  Gate.define('update-post', (user, post) => {
    return user.id === post.userId;
  }),
  Gate.define('doSomething', async (user) => {
    const hasPermissions = await someAsyncService.verifyPermissions(user);
    return hasPermissions;
  });
)
```

The idea is to wrap all `Gate.define` method inside another method called `Gate.withTypes` and then import this module inside the contracts file to read the type.

```ts
import Gates from '../start/authorization'

declare module '@ioc:Adonis/Addons/Authorization' {
  type GatesTypes = typeof Gates
  interface GateActions extends GatesTypes {}
}
```

All the magic of creating the correct types is done by the `Gate.withTypes` method. Here is a dummy working example of it 

https://bit.ly/3huV6rz

**Comment by targos** [comment]
That's interesting, I'm not opposed to it.
Do you think we'll be able to handle the Policy classes in a similar way? I can share the code I have done so far, if you want.

**Comment by targos** [comment]
How long are we supposed to wait for feedback before proceeding to the next step of the rfc?

**Comment by thetutlage** [comment]
I will look into it tonight and then we can plan the work. I don't others have much to add to this

**Comment by thetutlage** [comment]
@targos Take my sincere apologies. Have been really busy, that even looking at the issue felt too much.

I have been recently playing with these functional and OO style APIs to see which style fits better by keeping the Typescript constraints in place. I have realized, have a dedicated  self contained policy class makes a lot more sense vs registering the policy class using the `Gate.define` or `Gate.policy` method.

Just like the validator, I should be able to use the policy by just importing it.

```ts
import UserPolicy from 'App/Policies/User'

if (UserPolicy.allows('edit')) {

}
```

Also can you share what you have done so far?

**Comment by targos** [comment]
@thetutlage No worries, I totally understand. Time is a very limited resource :D

I agree that a self-contained policy class may make sense, but it couldn't be called as you showed here. Maybe something like this?

```js
import PostPolicy from 'App/Policies/PostPolicy'

if (await ctx.gate.allows(PostPolicy, 'edit', post)) {

}
```

- We need to call something on the context, so that the current authenticated user can be passed automatically
- We need to pass the object for which the policy is being applied

I haven't done much yet on the implementation, but it is not very difficult in practice. I am going to work on it this week, though.

**Comment by targos** [comment]
Do we agree on the above approach for class policies? To be clear, `PostPolicy.ts` would look like this:

```ts
export default class PostPolicy {
  edit(user: User, post: Post) {
    return user.id === post.userId
  }
}
```

**Comment by RomainLanz** [comment]
I agree with that, but I believe all of those methods should be async.

**Comment by targos** [comment]
I made a mistake in https://github.com/adonisjs/rfcs/issues/26#issuecomment-688786393. Gate methods are async

**Comment by thetutlage** [comment]
Yup, I am pretty much okay with the API and also agree that interferance of `ctx` will be required to pull the current user.

I can play with the initial draft and then give more feedback on it

**Comment by targos** [comment]
Okay, I'm going to continue and test the implementation in my private project and then will do a public sample app to iterate with you.

**Comment by thetutlage** [comment]
Sure. Looking forward to it :)

**Comment by targos** [comment]
Created a repo: https://github.com/targos/adonis-authorization-demo

**Comment by targos** [comment]
How do you want to collaborate on this? I have several questions about the implementation.

**Comment by thetutlage** [comment]
Lets jump in discord and talk about it

**Comment by targos** [comment]
I've been thinking about the "guest" use case (covered [here](https://laravel.com/docs/8.x/authorization#guest-users) in Laravel) and I think it's important and useful to support it.

Here's my proposition for it:

- By default, guests are not allowed. Gates and Policies automatically return `false` without calling the check method if there is no authenticated user.
- It is possible to opt into allowing guests on a case-by-case basis:

Gates: optional configuration in a third parameter for the `define` function:

```js
Gate.define('doSomething', async (user) => {
  if (!user) {
    return checkIfUnauthenticatedUserCanDoIt();
  }
  const hasPermissions = await someAsyncService.verifyPermissions(user);
  return hasPermissions;
}, {
  allowGuest: true
});
```

Policies: optional decorator on the method:

```ts
export default class PostPolicy {
  public create(user: User) {
    // User is guaranteed to be defined here.
    return user.isAdmin;
  }

  @allowGuest()
  public view(user?: User, post: Post) {
    // User could be undefined if guest, but still have access if the post is public.
    if (post.isPublic) return true;
    if (!user) return false;
    return user.id === post.userId;
  }
}
```

**Comment by dajpes** [comment]
Do it

**Comment by radiumrasheed** [comment]
I'm sorry to disrupt this conversation but I'll like to know if this is in any way related to RBAC?
Also, is RBAC going to be supported? when can we expect it.

Maybe also direct me to an article or even a 3rd plugin if it's not available yet

**Comment by thetutlage** [comment]
# Bouncer

> **DISCLAIMER:** The main goal of this comment is to capture the main idea and approach towards authorization. The final API may/will be a little different.

Here's my take on the same. I looked at [Laravel Gate](https://laravel.com/docs/8.x/authorization), [Pundit](https://github.com/varvet/pundit) and [Cancancan](https://github.com/CanCanCommunity/cancancan) for inspiration and decided that we should build something similar to Laravel Gate or Pundit.

There are two ways (in my limited knowledge) to approach authorization.

- Defining actions with a function that decides whether or not to authorize the user.
- Make use of declarative DSL that eliminates the need to write any custom functions and instead describes actions by writing a declarative JSON. For example:

  ```json
  // Admin
  {
    "role": "admin",
    "resources": "*"
  },

  // Editor
  {
    "role": "editor",
    "resources": {
      "post": ["edit", "update", "delete"]
    }
  },

  // Author
  {
    "role": "author",
    "resources": {
      "post": {
        "actions": ["create", "edit", "update"],
        "constraints": {
          "resource.user_id": {
            "eq": "$subject.id"
          }
        }
      }
    }
  }
  ```

  When using a DSL, it has to be super expressive to handle all the use cases (similar to IAM policies in AWS). In contrast, Javascript functions are more scalable to address all the needs.

> I look at the AdonisJS authorization module as a low-level API for **separating the business logic from the authorization logic**. Others are free to build on top of it as per their needs. For example, Laravel has this [permissions](https://github.com/spatie/laravel-permission) package, a layer on top of Laravel gates to have database driven RBAC system.

## Goals

Following is the list of rough goals I want to achieve

- Ability to define actions or abilities.
- Define filters. `before` and `after` and they work as a short-circuit.
- Define policies as classes. Mainly to scope actions for a given entity.
- Define a scope on policy to modify a database query based upon the user rights. For example: Limit the list of posts to the currently logged in user.
- Have support for middleware.
- Usage within views.
- Passing additional context.
- Should have great IntelliSense.
- Should allow for dynamic actions and policies. For example, database-driven permissions.

## Functional API

The simplest option is to have a functional API, just like Routes or Events.

```ts
import Bouncer from "@ioc:Adonis/Addons/Bouncer"
import User from "App/Models/User"
import Post from "App/Models/Post"

Bouncer.define("update_post", (user: User, post: Post) => {
  return user.id === post.user_id
})
```

The methods can be `async` as well and can also accept extra attributes.

```ts
import Bouncer from "@ioc:Adonis/Addons/Bouncer"
import User from "App/Models/User"
import Post from "App/Models/Post"
import Category from "App/Models/Category"

Bouncer.define("update_post", async (user: User, post: Post, category: Category) => {
  return user.id === post.user_id || category.name === "public"
})
```

To make IntelliSense work, we need to chain the `.define` calls and export them from the file registering Bouncer actions.

```ts
export default Bouncer
  .define("update_post", async (user: User, post: Post) => {
    return user.id === post.user_id || category.name === "public"
  })
  .define("delete_post", async (user: User, post: Post) => {
    return user.id === post.user_id
  })
```

I don't think chaining the `.define` will be a huge problem, or maybe it can be? I am not 100% sure and open to feedback. [Playground link](https://www.typescriptlang.org/play?ssl=9&ssc=10&pln=9&pc=52#code/C4TwDgpgBAggxsAlgewHYAkCGqAmAbCAJygF4oAKcgOhs0IHMBnALimxAG0BdASlID42qEFAA+UAAqFkAW0SMIAHnb8eAKDVw8mRoygAhZAFdUcIovhI0eiAA9gEXHoDeUDgGsIIVo2CFEqPRcrOxQAL6CzmpQMVBw1n5GCMjE5GBGAEZ4iHBsCCioLLD51nzOYRqxUOlZOVA4EABmAUqWBVB2Dk5Qvv6BADRQWLgExJ2OOHptaMP4RPzkmCWorNOogwAW2HOErLOjPKyGJmaEFst6AGRQUVVVHADSUAHFVqjBQ9uj0bERNz93CjADbyKhLN56HQ3NxPF5rD77IjhHgccEFLikKBbEZEAF3QgQYBGQioKDA+RsPTHUzmNZXaGPZ6k+F7L5IiJ4ioVTQJKAZYw04hkVAQADuBgFp3I5XUPMKwDJ4AgejI-JOuKqVAazRF5AA5EYwDhMA4APpgZC+PWDchGBS7aGIHCsVBGGQZdl8EiRMLqTXalr6hoEM0Wq02u1EViuJ0ut0e4i+gQ3X1AA)

The main goal is to use the runtime code for extracting static types vs. manually maintaining an interface.

## Using functional API

The usage will be as follows.

```ts
import Bouncer from "@ioc:Adonis/Addons/Bouncer"
import Post from "App/Models/Post"

const post = await Post.find(1)

if (await Bouncer.allows("update_post", post)) {
  await post.save()
}
```

Or use the authorize method.

```ts
import Bouncer from "@ioc:Adonis/Addons/Bouncer"
import Post from "App/Models/Post"

const post = await Post.find(1)
await Bouncer.authorize("update_post", post)

await post.save()
```

## Authorization class

The bouncer methods `allows,` `denies,` and `authorize` will create an instance of the `Authorization` class for a given `User`. The knowledge of a known user upfront will allow us to filter the available actions.

Check the [playground example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHYAkCGqAmAbCAJygF4oAKcgOhs0IHMBnALimxAG0BdASlID42qEFAA+UAAqFkAW0SMIAHnb8eAKFCQoAeTnAAYokKNgigCpQIAD2ARcjCjSp0mrdnxKCVpKBeu37Cis3YQAaKCcXFihEVAAzIkkPL2E1AEg0gH5JdLTWVAgANyI1Urg8TEYHGABXYAALZEJEAC9MJDRFAFVLGzscB3Zw+A7UB39+hwBvKA4AawgQVhNm1HouEJEAX0EptSgDqDg0FZqEJoowZsL26BqFQlYu8KvEG9s2BBQx1hHvxj4Uy2pUOUDANQARnhEHA2IwQKhYZg8HhkAB3RjmXoBAZQPag0EcADSMVQUAWIGQcVgXxOGxpo0YxK42MmFHuRCe4UiDGi7G4ySEImyJPyRRKoK280WVIZ-y4-HImFpqFYZm5NBw7UwrF0iAMRhMij+Jw4ZgVPFYUlk8iUEOQyAI2F2+wJB0IEGANUIZLiyIUroOwOBanKlQcACFkDVEURjSrxn1AjNpUsoCtYutNlAdnjA0cTsBCGdgBdyOCoTDPozfgnASHQRXobCcBA4rElCayRNAhm1uEsLgCMQe7iu4P8ERFcrRrXRuF6thJ48oBPh5aoFGY3A412HAAyPNug7E0lytD0tcSw65-HH8gNeTOBNwvGzEmxc+oS9L4c5ngcDO3wsmQi5Dteboel6PpQI+gyRtGsaEPGjJQIeKYfmSXY-uBxA7PmwZlBUVRQF0DxHocTZVqgmAyNAZAAOQcoQDGvscYzAGoIZhiRADCshgOwFEHFRsI0XRPgMccMiCcIrGVAWHFcUR4aSMgJh4txhZQPa26JGQBRopuiE7oQ5BAuoobaZoEAOGQulIfmVCtu2BTkExYBarYAD6YDqcADHhOQzFPA8Lz+Va-mChZTkuR27mtgQPl+SYgXsg8oVENFWzqKCzltvFDGFIgEBot5JjIHAcxpcFGVQPxMlDOmpZVcsRaZtllnsRpmB1I0zRtKMPiGbAfVNK07TfOQI1kUQ5A8OENmMM+jLqL1DTjYN3zOCi6KMO5NSebcvn+WlI0SP5808EAA) to see it in action, since explaining it in words is a little hard

- In the playground example, there are two entities/subjects, `Company` and `User`.
- We have defined a total of 3 actions. One for the `Company` and two for the `User`.
- If we pass an instance of `User` to the `AuthorizationClass`, it can narrow down the actions to the one's using the `User` class and vice-versa.

So basically, we need a way to know the exact type of the logged-in user or allow a way to pass in the user.

```ts
Bouncer.forUser(auth.user).allows("update_post")
```

## Policy classes

Policies are dedicated classes to define a set of actions for a given entity. For example:

```ts
import Post from "App/Models/Post"
import User from "App/Models/User"

class PostPolicy {
  public update(user: User, post: Post) {
    return user.id === post.user_id
  }
}
```

Unlike Laravel, I do not want the policies to be tied to a model. Instead, they should be able to work with any piece of data.

For example, I should be able to create a policy for a dashboard that decides which widgets to show on the dashboard and will usually be dealing with multiple models.

When policies are not tied to a model, there is no hard requirement to register them upfront. For example: In Laravel uses the **model instance** or the **model class** to find the policy to use.

### Following is the Laravel code

```php
protected $policies = [
  Post::class => PostPolicy::class,
];

// and use it as
Gate::authorize('update', $post);
```

Now, they will use the `$post` variable to know which policy to use. I don't want to go this route as it is tough to perform this detection beyond classes.

### AdonisJS Approach

Instead, I want the policies used to be like the following example

```ts
Bouncer
  .use(() => import("App/Policies/PostPolicy"))
  .authorize("update", post)
```

The `use` method accepts a callback in which you import the policy you want to use. This way, we also get the IntelliSense for all the actions defined inside the policy class.

An alternative way can be to register your policies within a unique name at the boot time.

```ts
export default Bouncer
  .registerPolicies({
     PostPolicy: () => import("App/Policies/PostPolicy"),
  })
  .define('inline_action', () => {})

// Usage
Bouncer.use("PostPolicy").authorize("update", post)
```

## Usage inside views

Usage inside views is a little challenging for the following reasons.

- Figure out the way to import policies inside views.
- Using the `await` keyword. If the policy has an `async` implementation.

The 2nd is still doable, as we just need to enable async rendering of views. However, importing policies is a bit difficult, as it also makes the syntax verbose. For example:

```html
@if(await bouncer.use(() => import('App/Policies/PostPolicy')).authorize('update', post))
  // markup
@endif
```

🤮Not desirable.

Instead, we can try something like this.

```html
@can('App/Policies/PostPolicy.update', post)
@endcan
```

Or if the policy was pre-registered, then we can use just the name.

```html
@can('PostPolicy.update', post)
@endcan
```

## Middleware Usage

The middleware will follow a similar approach as the views. Using the `namespace.action_name`.

```ts
Route
  .put("posts/:id", "PostsController.update")
  .middleware("can:App/Policies/PostPolicy.update")
```

With pre-registered policy, it will be

```ts
Route
  .put("posts/:id", "PostsController.update")
  .middleware("can:PostPolicy.update")
```

## Policies vs `Bouncer.define`

Both are standalone actions requiring data to decide to allow or disallow a user from taking action.

The `Bouncer.define` is in the global namespace. Meaning, you can access them just by the action name. Whereas, `Policies` actions uses a namespace inside a given class. \
**Otherwise, there is no difference.**

## Scopes

Along with the actions, one should be able to define a scope inside the policy class. The goal of the scope is to add a constraint to a query for a given user. This is usually going to be helpful for filtering a collection of resources and one scope should do the job for a policy.

```ts
import User from "App/Models/User"
import Post from "App/Models/Post"

class PostPolicy {
  public policyScope(user: User, query: ReturnType<Post.query>) {
    // Can see all
    if (user.role === "admin" || user.role === "editor") {
      return
    }

    // Author can see published posts or their own drafts
    if (user.role === "author") {
      query.where("is_published", true).orWhere("user_id", user.id)
    }

    // Others can see published posts only
    return query.where("is_published", true)
  }
}
```

### Usage

```ts
await Bouncer.use('PostPolicy').scope(Post.query()).paginate(1, 20)
```

## Dynamic actions + policies

It needs a bit more research and real-time use cases to allow dynamic actions + policies and have some level of type safety. Will scratch the surface after the initial implementation of Bouncer

**Comment by targos** [comment]
It seems good in general!

I have few questions:
- With the Policy API, if I want to check if someone can "create" something (so I don't have an instance of that thing), would I just call `Bouncer.use('PostPolicy').allows('create')` ? And `Bouncer.use('PostPolicy').allows('create', something)` if there's an additional parameter? And the fact that I don't need to pass a Post is because the `Policy#create` method doesn't have it in its parameters?
- All your examples seem to use `Bouncer` from the import, but to have access to the currently logged in user, you need to be in a request context. In my implementation, I added `ctx.gate` for it (which is a shortcut for `Gate.forUser(ctx.auth.user)`)
- Your proposal doesn't mention "guest" users. If they are not initially supported, I think it should explicitly forbid them (do as if the policy method returned `false` without calling it)
- Why have `Bouncer.use(() => import("App/Policies/PostPolicy"))` instead of just passing the `PostPolicy` class directly? There is little benefit and great inconvenience (having to write an arrow function everytime, having to go through the module loader everytime) imo in this case.

**Comment by thetutlage** [comment]
> With the Policy API, if I want to check if someone can "create" something (so I don't have an instance of that thing), would I just call Bouncer.use('PostPolicy').allows('create') ? And Bouncer.use('PostPolicy').allows('create', something) if there's an additional parameter? And the fact that I don't need to pass a Post is because the Policy#create method doesn't have it in its parameters?

Yes, you won't have to pass any params, since the policy `create` action doesn't require any arguments.

> All your examples seem to use Bouncer from the import, but to have access to the currently logged in user, you need to be in a request context. In my implementation, I added ctx.gate for it (which is a shortcut for Gate.forUser(ctx.auth.user))

Yup, did that for the sake of simplicity. But, there will be a `ctx.bouncer` 

> Your proposal doesn't mention "guest" users. If they are not initially supported, I think it should explicitly forbid them (do as if the policy method returned false without calling it)

Yeah, I am little unsure why the guest requests have to go through authorization at all in first place. Do you have any example, where you are already doing this?

> Why have Bouncer.use(() => import("App/Policies/PostPolicy")) instead of just passing the PostPolicy class directly? There is little benefit and great inconvenience (having to write an arrow function everytime, having to go through the module loader everytime) imo in this case.

Ohh, I felt it the other way around. I personally hate too many imports at the top of my files and always look for ways to inline them whenever possible. But yes, this is a subjective choice.

And you can pass the policy class directly as well. 

Another option to register policies with an identifier called the resource name and use that instead. For example:

```ts
Bouncer.registerPolicies({
  'PostPolicy': () => import('App/Policies/Post') // Lazy loading in this case
})
```

and then use it as

```ts
Bouncer.use('PostPolicy')
```

This is also going to be a preferred way within the edge templates.

**Comment by targos** [comment]
> Yeah, I am little unsure why the guest requests have to go through authorization at all in first place. Do you have any example, where you are already doing this?

Imagine I'm re-implementing GitHub with AdonisJS. If you try to access a private repo URL without being authenticated (guest), you get a 404 error. If you try to access a public repo, you can view it.

Other similar example: in one of my applications, entries are private by default, but users can make them public, which enables anyone, even guests to view them and to query them by the API.

**Comment by thetutlage** [comment]
Alright, so the action code for this will look something like

```ts
Bouncer.define('view-repo', (user, repo) => {
  if (repo.public) {
    return true
  }

  if (!user) {
    return false
  }

  // some other checks
})
```

**Comment by targos** [comment]
Yes, the code would look like this. The point of explicitly having to opt-in for guests is that if we don't do it, you could forget about it when you implement the action code and incorrectly allow guests where you shouldn't.
Also, when there is a guest, `user` is not a `User` object. In my implementation it's `null` so you also have to handle that in all actions unless guests are not allowed by default and the method isn't called for them.

**Comment by thetutlage** [comment]
Yup got it. So basically you have to opt-in explicitly to allow for guest users and only in that case mark the `user` as an instance of User or null. It has to be null, coz we cannot have first argument as optional and 2nd as required.

Something like this

```ts
Bouncer.define('view-repo', (user: User | null, repo) => {
  if (repo.public) {
    return true
  }

  if (!user) {
    return false
  }

  // some other checks
}, { allowGuest: true })
```

But now, the question is, how you do it within the policy at per method level? Using decorator as you mentioned earlier?

```ts
class PostPolicy {
  @allowGuest()
  public update(user: User | null, post: Post) {
    return user && user.id === post.user_id
  }
}
```

Another option is to move the `User` at the constructor level

```ts
class PostPolicy {
  public static allowGuest = true

  constructor(public user: User | null) {}

  public update(post: Post) {
    return this.user && this.user.id === post.user_id
  }
}
```

**Comment by targos** [comment]
I implemented it with a decorator (https://github.com/zakodium/adonis-authorization/blob/cb921ce998e98ecdba36447316be374497b07656/src/__tests__/Gate.test.ts#L319) but am open to other ideas.

> Another option is to move the User at the constructor level

Not a big fan of this because it requires to define the constructor everywhere and I can easily see that only a few methods could allow guests, not always all or none.

**Comment by thetutlage** [comment]
Yeah, not 100% in favour of constructor too. Each action should have its own set of params. But still wanted to bounce the idea.
